name: ScaleChanger
version: '${version}'
main: ru.fennec.free.scaleChanger.scaleChanger.ScaleChangerPlugin
api-version: '1.20'
authors: [ BuseSo ]
description: Меняйте размер игрока одной командой
website: https://spigotmc.ru/members/307/

commands:
  scalechanger:
    description: Главная команда плагина
    aliases: [scale,fenscale,busescale]
